// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Dqo9i0A4x-1hGq3VU-PQbXmpYBKxCAU',
    appId: '1:631475575592:web:b54b026d36684d826ace1d',
    messagingSenderId: '631475575592',
    projectId: 'test-ultilites',
    authDomain: 'test-ultilites.firebaseapp.com',
    storageBucket: 'test-ultilites.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNyV_pWcxwQdiR4gn0dSVxouopqtbthP0',
    appId: '1:631475575592:android:5be56e52ece687b56ace1d',
    messagingSenderId: '631475575592',
    projectId: 'test-ultilites',
    storageBucket: 'test-ultilites.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxAfm-B84bj21_N14dQ__u29CgE2x3bkM',
    appId: '1:631475575592:ios:021721f341f5c7f06ace1d',
    messagingSenderId: '631475575592',
    projectId: 'test-ultilites',
    storageBucket: 'test-ultilites.appspot.com',
    iosBundleId: 'com.example.flutterHealthMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxAfm-B84bj21_N14dQ__u29CgE2x3bkM',
    appId: '1:631475575592:ios:021721f341f5c7f06ace1d',
    messagingSenderId: '631475575592',
    projectId: 'test-ultilites',
    storageBucket: 'test-ultilites.appspot.com',
    iosBundleId: 'com.example.flutterHealthMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Dqo9i0A4x-1hGq3VU-PQbXmpYBKxCAU',
    appId: '1:631475575592:web:ba0ee8771ff854426ace1d',
    messagingSenderId: '631475575592',
    projectId: 'test-ultilites',
    authDomain: 'test-ultilites.firebaseapp.com',
    storageBucket: 'test-ultilites.appspot.com',
  );
}
